name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Navigate to project directory
        working-directory: ./steppi1
        run: echo "Moved to /steppi1"
      - name: Install dependencies
        working-directory: ./steppi1
        run: npm ci
      - name: Build the project
        working-directory: ./steppi1
        run: npm run build --if-present
      - name: Run tests
        working-directory: ./steppi1
        run: npm test
